import{a as w,S as L,i as a}from"./assets/vendor-mdVVRe9K.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))s(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function t(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(o){if(o.ep)return;o.ep=!0;const r=t(o);fetch(o.href,r)}})();const E="https://pixabay.com/api/",b="45735019-5668e0368fbdb80eca42c52b3";let d=1;async function g(n){try{const e=await w.get(E,{params:{key:b,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:d}});return d+=1,e.data}catch(e){throw console.error("Error fetching images:",e),e}}function I(){d=1}const B=document.getElementById("gallery"),m=document.getElementById("load-more"),y=document.getElementById("loading"),v=new L(".gallery a",{captionsData:"data-caption",captionDelay:250});function p(n){const e=n.map(t=>`
                <a class="card" href="${t.largeImageURL}" data-caption="
                    <p>Likes: ${t.likes}</p>
                    <p>Views: ${t.views}</p>
                    <p>Comments: ${t.comments}</p>
                    <p>Downloads: ${t.downloads}</p>
                ">
                    <img src="${t.webformatURL}" alt="${t.tags}">
                    <div class="card-info">${t.tags}</div>
                </a>
            `).join("");B.insertAdjacentHTML("beforeend",e),v.refresh()}function M(){m.style.display="block"}function i(){m.style.display="none"}function h(){y.style.display="block"}function f(){y.style.display="none"}function P(){a.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"})}function u(){a.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})}const $=document.getElementById("search-form"),O=document.getElementById("load-more");let c="";$.addEventListener("submit",async n=>{if(n.preventDefault(),c=document.getElementById("search-input").value.trim(),!c){a.error({title:"Error",message:"Search field cannot be empty!"});return}I(),i(),document.getElementById("gallery").innerHTML="";try{h();const e=await g(c),{hits:t,totalHits:s}=e;t.length===0?P():(p(t),t.length<15||s<=15?(i(),u()):M())}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{f()}});document.addEventListener("DOMContentLoaded",()=>{i(),f()});O.addEventListener("click",async()=>{try{h();const n=await g(c),{hits:e,totalHits:t}=n;e.length===0?(i(),u()):(p(e),(e.length<15||t<=15)&&(i(),u()));const s=document.querySelector(".card");s&&window.scrollBy({top:s.getBoundingClientRect().height*2,behavior:"smooth"})}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{f()}});
//# sourceMappingURL=index.js.map
