import{a as w,S as b,i as u}from"./assets/vendor-mdVVRe9K.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))t(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&t(c)}).observe(document,{childList:!0,subtree:!0});function s(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(o){if(o.ep)return;o.ep=!0;const r=s(o);fetch(o.href,r)}})();const L="https://pixabay.com/api/",E="45735019-5668e0368fbdb80eca42c52b3";let l=1;async function f(n){try{const e=await w.get(L,{params:{key:E,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:l}});return l+=1,e.data}catch(e){throw console.error("Error fetching images:",e),e}}function I(){l=1}const B=document.getElementById("gallery"),g=document.getElementById("load-more"),m=document.getElementById("loading");function y(n){const e=n.map(t=>`
                <a class="card" href="${t.largeImageURL}" data-caption="
                    <p>Likes: ${t.likes}</p>
                    <p>Views: ${t.views}</p>
                    <p>Comments: ${t.comments}</p>
                    <p>Downloads: ${t.downloads}</p>
                ">
                    <img src="${t.webformatURL}" alt="${t.tags}">
                    <div class="card-info">${t.tags}</div>
                </a>
            `).join("");B.insertAdjacentHTML("beforeend",e),new b(".gallery a",{captionsData:"data-caption",captionDelay:250}).refresh()}function v(){g.style.display="block"}function i(){g.style.display="none"}function h(){m.style.display="block"}function p(){m.style.display="none"}function P(){u.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"})}function d(){u.info({title:"End of results",message:"We're sorry, but you've reached the end of search results."})}const $=document.getElementById("search-form"),M=document.getElementById("load-more");let a="";$.addEventListener("submit",async n=>{if(n.preventDefault(),a=document.getElementById("search-input").value.trim(),!a){iziToast.error({title:"Error",message:"Search field cannot be empty!"});return}I(),i(),document.getElementById("gallery").innerHTML="";try{h();const e=await f(a),{hits:s,totalHits:t}=e;s.length===0?P():(y(s),s.length<15||t<=15?(i(),d()):v())}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{p()}});M.addEventListener("click",async()=>{try{h();const n=await f(a),{hits:e,totalHits:s}=n;e.length===0?(i(),d()):(y(e),(e.length<15||s<=15)&&(i(),d()));const t=document.querySelector(".card");t&&window.scrollBy({top:t.getBoundingClientRect().height*2,behavior:"smooth"})}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{p()}});
//# sourceMappingURL=index.js.map
